/*
 * Copyright (C) 2024 Abdalla Bushnaq
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.bushnaq.abdalla.engine.audio;


import de.bushnaq.abdalla.engine.event.IEventManager;

public interface CommunicationPartner {
    long RADIO_ANSWER_DELAY = 4000;//ms

    IEventManager getEventManager();

    int getId();

    String getName();

    boolean isSelected();

    void notifyFinishedTalking(RadioMessage msg);

    void notifyStartedTalking(RadioMessage message);

    /**
     * Process the incoming radio message request.
     * if it is a spaken message, it needs to be generated by the chat agent first,
     * then spoken by the TTS engine.
     *
     * @param rm The RadioMessage containing the message details.
     */
    void processRadioMessage(RadioMessage rm);

    void select() throws OpenAlException;

    void unselect() throws OpenAlException;
}
